dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.43.0
    - rust: 1.46.0
    - rust: 1.49.0

before_install:
  - set -e
  - rustup self update

script:
  - cargo test

after_script: set +e
